# Generated by Django 5.1.2 on 2024-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_team_name_remove_tournament_number_of_courts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('group_elimination', 'Gruppenphase + KO-Runde'), ('swiss', 'Schweitzer System'), ('round_robin_once', 'Jeder gegen Jeden nur Hinrude'), ('round_robin_twice', 'Jeder gegen Jeden Hin- und Rückrunde')], default='round_robin_once', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('started', 'Started')], default='planned', max_length=10),
        ),
    ]
